In [7]:
import numpy as np
import tensorflow as tf
import time

In [28]:
A = np.random.randn(9, 9)
print A

[[ 1.91262572  0.30116147  2.32561185  1.44594227  0.03438064 -1.53254074
  -0.77753298 -0.85298794  0.12143519]
 [-0.11200148  1.41171223  0.81708483  0.83008592  1.32460523  0.8363351
   0.7910425   0.50512791 -0.1883296 ]
 [-0.03212866 -0.49122985  1.21769845 -0.20152082 -1.33636823  1.89651136
  -0.52708327  0.57959347 -0.54221721]
 [-0.32062638  0.77767273 -0.932021   -0.07488679  1.59621232  0.57207699
   0.25932869  1.5242227   0.86105017]
 [ 0.34227937  1.2691452   0.19051082 -0.73503294 -0.78464565  2.12316261
   0.41495565  0.13378825 -0.43470122]
 [-0.33316774 -1.00948066  0.02301058  1.29597279 -0.28855185  0.43510315
  -0.07160062 -1.17543638  0.04141811]
 [ 0.31338501 -1.4311644   1.41977284 -0.71842067 -0.76198118  0.24172716
   0.87316049  0.30799863 -0.93421089]
 [ 0.13034651 -0.41210075 -0.0765879  -1.30487103 -1.85744759 -1.65567144
   0.23058729  1.58995073 -1.7185473 ]
 [ 0.72378465 -0.01270667  0.73500864  0.57385142  0.83842119 -1.67387052
  -1.90506359 -0.055181

In [29]:
# create placeholders for co-occurrence matrix
X = tf.placeholder(tf.float32, [9, 9], name='co_occurrence_matrix') 

# run SVD
s, u, v = tf.svd(X)

with tf.Session() as sess:

    print 'Running SVD...'
    
    start_time = time.time()

    s, u, v = sess.run([s, u, v], feed_dict={X: A})

    print 'Total time: {0} seconds'.format(time.time() - start_time)
    print 'SVD Finished!'

Running SVD...
Total time: 0.00494599342346 seconds
SVD Finished!


In [34]:
print np.dot(u, np.dot(np.diag(s), v.T))
print A

[[ 1.91262698  0.30116144  2.32561255  1.44594264  0.03437987 -1.53254223
  -0.7775327  -0.8529883   0.12143523]
 [-0.11200219  1.41171324  0.81708574  0.8300873   1.32460499  0.83633703
   0.79104328  0.5051282  -0.18833011]
 [-0.03212845 -0.49122992  1.21770048 -0.20151986 -1.3363688   1.89651453
  -0.52708352  0.57959437 -0.54221749]
 [-0.32062668  0.77767301 -0.9320215  -0.07488673  1.59621286  0.57207793
   0.2593284   1.5242244   0.86105132]
 [ 0.34228033  1.26914656  0.1905122  -0.73503345 -0.78464657  2.12316608
   0.41495648  0.13378763 -0.43470144]
 [-0.33316755 -1.00948191  0.02301069  1.29597461 -0.28855222  0.43510368
  -0.07160034 -1.17543733  0.04141787]
 [ 0.31338537 -1.43116486  1.41977394 -0.7184208  -0.76198244  0.24172775
   0.87316012  0.30799839 -0.93421161]
 [ 0.13034737 -0.4121007  -0.07658847 -1.30487108 -1.85744894 -1.65567493
   0.23058738  1.58995187 -1.71854937]
 [ 0.7237848  -0.01270741  0.73500931  0.57385075  0.83842206 -1.67387402
  -1.9050653  -0.05518

In [33]:
print u.shape, s.shape, v.shape
print s

(9, 9) (9,) (9, 9)
[ 5.02907324  4.5867281   3.75913978  3.08060265  1.97808158  1.82521296
  1.32623386  1.03636217  0.44758782]


In [36]:
e = 3
print u[:,:e].shape
print u[:,:e]

(9, 3)
[[ 0.65079564  0.22242045  0.36381394]
 [-0.15102936  0.2780138   0.24118939]
 [-0.08611432 -0.36214161  0.5082134 ]
 [-0.34468564  0.27733958 -0.25431749]
 [-0.32360676 -0.18543552  0.39562669]
 [ 0.07634186  0.07841525  0.25392857]
 [ 0.1084754  -0.43258595  0.23476115]
 [ 0.19551615 -0.64773113 -0.43437108]
 [ 0.51661241  0.13398705 -0.1473725 ]]
